#!/usr/bin/env bash
# push <options> <user@host> <file/directory> <destination>
#
# example: bash push -e "./.ignore" user@127.0.0.1 ~/Workspace /www
# example: bash push -WD -i "file-1.txt","file-2.txt" user@127.0.0.1 / /

if [ "$1" == "-h" ];
then
    echo "
 push <options> <user@host> <file/directory> <destination>

 <options>
    -i              exclude list: \"file-1.txt\",\"file-2.txt\"
    -e              exclude file: \"./.ignore\" (default: ./.ignore)
    -W              upload directory starts with: /Workspace
    -D              destination directory starts with: /www

 <user@host>
    example         SSH user name and IPv4 address: user_name@127.0.0.1

 <file/directory>
    file            file path: /path/to/file.ext
    directory       directory path: /path/to/directory

 <destination>
    destination     host destination directory: /path/to/directory
    "
    exit 1
fi

user_host=${@: -3:1}
file_directory=${@: -2:1}
destination=${@: -1}

exclude_file=( --exclude-from="./.ignore" )
exclude_list="null"

if [[ ! $destination =~ ^\/ ]];
then
    echo "The host destination directory should start with -> / <- ($destination)."
    exit 1
fi

while getopts "e:i:WD" opt;
   do
     case $opt in
        e )
            [[ -f $OPTARG ]] && exclude_file=( --exclude-from=$OPTARG )
            ;;
        i )
            arr=()
            IFS="," read -ra OPTS <<< "$OPTARG"
            for i in "${OPTS[@]}"; do
                arr+=( --exclude="$i" )
            done
            exclude_list=( ${arr[@]} );;
        W )
            file_directory="$HOME/Workspace$file_directory";;
        D )
            destination="/www$destination";;
        * )
            break;;
     esac
done

if [[ $user_host =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
then
    echo "$user_host is valid."
else
    if [[ ! $user_host =~ \@ ]]
    then
        echo "$user_host is not valid! @ character is missing!"
        exit 1
    fi

    if [[ $user_host =~ ^[a-zA-Z\_\.\-]+\@[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
    then
        echo "$user_host is valid."
    else
        echo "$user_host is not valid! Allowed characters for user names [a-zA-Z\_\.\-]+. If something is missing, add your special character to the list."
        exit 1
    fi
fi

if [[ -d $file_directory ]]; 
then
    echo "$file_directory is valid."
elif [[ -f $file_directory ]];
then
    echo "$file_directory is valid."
else
    echo "$file_directory is not valid! Seems that $file_directory does not exists."
    exit 1
fi

[[ ${exclude_list[@]} == "null" ]] && exclude=${exclude_file[@]} || exclude=${exclude_list[@]}

if [[ ! $file_directory =~ \/$ ]];
then
    while true; do
    read -p "Are you sure to synchronize $(tput bold)$(tput setaf 1)$file_directory$(tput sgr0) with $(tput bold)$(tput setaf 1)$destination$(tput sgr0) (yes/no)? " answer
        case "$answer" in
            yes )
                exec rsync -vr ${exclude[@]} --delete $file_directory $user_host:$destination
                break;;
            no )
                echo "Ok, maybe later."
                break;;
            *)
                echo "Please, try again (yes/no).";;
        esac
    done
elif [[ $file_directory =~ \/$ ]];
then
    while true; do
    read -p "Are you sure to synchronize $(tput bold)$(tput setaf 1)all files $files_directory$(tput sgr0) with $(tput bold)$(tput setaf 1)the directory $destination$(tput sgr0) (yes/no)? " answer
        case "$answer" in
            yes )
                exec rsync -vr ${exclude[@]} --delete $file_directory $user_host:$destination
                break;;
            no )
                echo "Ok, maybe later."
                break;;
            *)
                echo "Please, try again (yes/no).";;
        esac
    done
else
    while true; do
    read -p "Are you sure to synchronize $(tput bold)$(tput setaf 1)the file $files_directory$(tput sgr0) with $(tput bold)$(tput setaf 1)the directory $destination$(tput sgr0) (yes/no)? " answer
        case "$answer" in
            yes )
                exec rsync -vr ${exclude[@]} --delete $file_directory $user_host:$destination
                break;;
            no )
                echo "Ok, maybe later."
                break;;
            *)
                echo "Please, try again (yes/no).";;
        esac
    done
fi